import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface":                    "#0e141e",
        "surface-dim":                "#0e141e",
        "surface-bright":             "#333945",
        "surface-container-lowest":   "#080e18",
        "surface-container-low":      "#161c26",
        "surface-container":          "#1a202a",
        "surface-container-high":     "#242a35",
        "surface-container-highest":  "#2f3540",
        "surface-variant":            "#2f3540",
        "on-surface":                 "#dde2f1",
        "on-surface-variant":         "#d4c5ab",
        "on-background":              "#dde2f1",
        "background":                 "#0e141e",
        "outline":                    "#9c8f78",
        "outline-variant":            "#4f4632",
        "primary":                    "#ffe4af",
        "primary-fixed":              "#ffdf9e",
        "primary-fixed-dim":          "#fabd00",
        "primary-container":          "#ffc107",
        "on-primary":                 "#3f2e00",
        "on-primary-fixed":           "#261a00",
        "on-primary-fixed-variant":   "#5b4300",
        "on-primary-container":       "#6d5100",
        "inverse-primary":            "#785900",
        "secondary":                  "#70d8c8",
        "secondary-fixed":            "#8df5e4",
        "secondary-fixed-dim":        "#70d8c8",
        "secondary-container":        "#32a192",
        "on-secondary":               "#003731",
        "on-secondary-fixed":         "#00201c",
        "on-secondary-fixed-variant": "#005048",
        "on-secondary-container":     "#00302a",
        "tertiary":                   "#dce7ff",
        "tertiary-fixed":             "#d8e3fb",
        "tertiary-fixed-dim":         "#bcc7de",
        "tertiary-container":         "#c0cbe3",
        "on-tertiary":                "#263143",
        "on-tertiary-fixed":          "#111c2d",
        "on-tertiary-fixed-variant":  "#3c475a",
        "on-tertiary-container":      "#4b566a",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
        "inverse-surface":            "#dde2f1",
        "inverse-on-surface":         "#2b313c",
        "surface-tint":               "#fabd00",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
